server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/tk?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: "084032"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 127.0.0.1
    username: taikang
    password: taikang
    virtual-host: /taikang
    template:
      retry: #失败重试
        enabled: true #开启失败重试
        initial-interval: 10000ms #第一次重试的间隔时长
        max-interval: 30000ms #最长重试间隔，超过这个间隔将不再重试
        multiplier: 2 #下次重试间隔的倍数，此处是2即下次重试间隔是上次的2倍
      exchange: ly.item.exchange
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
tk:
  jwt:
    pubKeyPath: D:\tmp\rsa\rsa.pub #公钥地址
    cookieName: TK_TOKEN
  worker:
    workerId: 1
    dataCenterId: 1
  pay:
    appId:
    mchId:
    key:
    connectTimeoutMs:
    readTimeoutMs:
    notifyUrl:
